config/routes.rb
Rails.application.routes.draw do

  resources :cocktails, only: [ :index, :show, :create ] do
    resources :doses, only: [:create]
  end
  resources :doses, only: :destroy

  root to: "cocktails#index"
  # delete "doses/:id", to: "doses#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses


  validates :name, uniqueness: true, presence: true

  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail_id, presence: true
  validates :ingredient_id, presence: true
  validates :ingredient_id, uniqueness: { scope: :cocktail_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show]

  def index
    cocktail_names = Cocktail.all.map {|cocktail| cocktail[:name]}
    if params[:query].nil?
      @cocktails = Cocktail.all
    elsif cocktail_names.include?(params[:query])
      @cocktails = Cocktail.where(name: params[:query])
    else
      @cocktails_all = Cocktail.all
      @cocktails = []
      @cocktails_all.each do |cocktail|
        cocktail.ingredients.each do |ingredient|
          if ingredient[:name] == params[:query]
          @cocktails << cocktail
          end
        end
      end
    end
    @cocktail = Cocktail.new
  end

  def show
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_param)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_param
    params.require(:cocktail).permit(:name, :photo, :description)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:create]

  def create
    @dose = Dose.new(params_dose)
    @dose.cocktail = set_cocktail
    if @dose.save
      redirect_to cocktail_path(set_cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private
  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def params_dose
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
    <div class="container">
      <div class="row">
        <% @cocktails.each do |cocktail| %>
        <div class="col-xs-12 col-sm-4 card-link">
          <%= link_to cocktail_path(cocktail) do %>
          <% if cocktail[:photo].nil? == false %>
            <div class="card" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= cl_image_path cocktail.photo, crop: :fill%>')">
          <% else %>
            <div class="card" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://gettaphunter.com/wp-content/uploads/2016/08/bar-11.jpg')">
          <% end %>
              <div class="card-description">
                <h2><%= cocktail.name %></h2>
                <% if cocktail.doses.count != 0 %>
                <p>Number of ingredients : <%= cocktail.doses.count %></p>
                <% else %>
                <p>Complète ton Cocktail !</p>
                <% end %>
              </div>
            </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>


<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">New Cocktail</h4>
      </div>
      <div class="modal-body">
          <%= simple_form_for @cocktail, class: "form-group" do |f| %>
            <%= f.input :name %>
            <%= f.input :description %>
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
            <div class="modal-footer">
            <%= f.submit "add a coktail", class: "btn btn-primary" %>
            </div>
            <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
          <%= simple_form_for @cocktail, class: "form-group" do |f| %>
            <%= f.input :name %>
            <%= f.input :description %>
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
            <%= f.submit "add a coktail", class: "btn btn-primary" %>
          <% end %>

app/views/cocktails/show.html.erb
<% if @cocktail[:photo].nil? == false %>
  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= cl_image_path @cocktail.photo, crop: :fill%>')">
<% else %>
  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://gettaphunter.com/wp-content/uploads/2016/08/bar-11.jpg')">
<% end %>
  <div class="banner-content">
    <h1><%= @cocktail.name %></h1>
  </div>
</div>

<div class="container">
  <div class = "cocktail">
    <div class="description">
      <h3> Description </h3>
      <p> <%= @cocktail.description %></p>
    </div>
    <div class = "ingredient">
      <h3> Ingredients </h3>
      <ul class = "dose-list">
        <% @cocktail.doses.each do |dose| %>
        <li class = "cocktail-dose">  <%= dose.ingredient.name %> - <%= dose.description %>
          <%= link_to dose_path(dose), method: :delete,
          data: { confirm: "are you sure?"} do %>
          <i class="fa fa-trash-alt" aria-hidden="true"></i>
          <% end %>
        </li>
        <% end %>
        <button type="button" class="btn btn-treehouse" data-toggle="modal" data-target="#ingredientModal" data-whatever="" id="ingredient">Add an ingredient</button>
      </ul>
    </div>
  </div>
  <%= link_to "Back to Cocktails list", cocktails_path, class: "btn btn-treehouse" %>
</div>


<div class="modal fade" id="ingredientModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">New ingredient</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@cocktail, @dose] do |f| %>
          <%= f.input :description %>
          <%= f.association :ingredient, prompt: "Choose an ingredient" %>
          <div class="modal-footer">
            <%= f.submit "add a dose", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient, prompt: "Choose an Ingredient" %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar-wagon">
      <button type="button" class="btn btn-medium" data-toggle="modal" data-target="#myModal" data-whatever="@fat">New Cocktail</button>
      <form action="/cocktails">
      <input type="text" placeholder="Search for a cocktail or an ingredient..." name="query" class="search-form">
      <input type="submit" value="filter">
      </form>
    </div>

    <%= yield %>


    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>